---

repo: https://download.docker.com/linux/centos/docker-ce.repo

packages_docker_engine:
- docker-ce-19.03.14-3.el8 
- containerd.io

services_docker_engine:
- docker

packages:
- kubelet
- kubeadm
- kubectl

packages_disable_excludes:
- kubernetes

services:
- kubelet

worker_ports:
- "10250/tcp"
- "8285/udp"
- "8472/udp"
- "30000-32767/tcp"