- hosts: kubernetes-master-nodes:kubernetes-worker-nodes:fns-nodes
  become: yes
  vars_files:
  - "group_vars/init_vars.yaml"
  
  tasks:
  - name: Actualización a ultimo nivel
    dnf:
     update_only: yes
       
  - name: Configuracion de la sincronizacion horaria
    shell: timedatectl set-timezone "{{ timezone }}"
    
  - name: Instalando paquetes basicos
    dnf:
      name: "{{ initpackages }}"  
      state: present
    
  - name: Inicializando servicios basicos
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items: "{{ initservices }}"  
    
  - name: Configuracion de la sincronizacion horaria
    shell: timedatectl set-ntp true
    
  - name: Se desactiva SELinux
    lineinfile:
      dest: /etc/selinux/config
      regexp: 'SELINUX=enforcing$'
      line: "SELINUX=disabled"
      state: present
      backrefs: yes