- hosts: nfs-nodes
  become: yes
  vars_files:
  - "group_vars/env_nfs.yaml"
  
  tasks:

  - name: Creando el grupo del volumen
    lvg:
      pvs: "{{ data_disk }}"
      vg: data_vg
      state: present

  - name: Creando el volumen logico
    lvol:
      vg: data_vg
      lv: nfs_lv
      size: "2559"
      state: present
      force: yes
  
  - name: Creando el filesystem de tipo XFS
    filesystem:
      fstype: xfs
      dev: /dev/data_vg/nfs_lv
      force: yes
      resizefs: yes
  
  - name: Creamos el punto de montaje
    file:
      path: /srv/nfs
      state: directory
  
  - name: Incluimos el volumen logico en el fichero para que se monte en el arranque
    lineinfile:
      regexp: dev/data_vg/nfs_lv /srv/nfs xfs  defaults  0 0 
      dest: /etc/fstab
      line: /dev/data_vg/nfs_lv /srv/nfs xfs  defaults  0 0
    
  - name: Se instala el paquete NFS
    dnf:
      name: "{{ nfs_packages }}"
      state: latest
      
  - name: Inicializando servicios nfs
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items: "{{ nfs_services }}"        
  
  - name: Abre el firewall para los servicios indicados
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    with_items: " {{ firewall_nfs_services }}"

  - name: Se indican los host con acceso al NFS
    lineinfile:
      path: /etc/exports  
      regexp: "/srv/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)"    
      line: "/srv/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)" 
      create: yes
    with_items:
      - "{{ groups['kubernetes-master-nodes'] }}"
      - "{{ groups['kubernetes-worker-nodes'] }}"

  - name: Se aplica la nueva configuracion
    shell: exportfs -r
