---
- hosts: kubernetes-master-nodes:kubernetes-worker-nodes
  become: yes
  vars_files:
  - "group_vars/env_global.yaml"
  tasks:
  
  - name: Pone la IPs a /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"   
  
  - name: Activar transparent masquerading para que los PODs puedan comunicarse dentro del cluster mediante VXLAN
    shell: modprobe br_netfilter
        
  - name: Activar transparent masquerading para que los PODs puedan comunicarse dentro del cluster mediante VXLAN (firewall)
    firewalld:
      masquerade:
      state: enabled
      permanent: yes
      immediate: yes
      
  - name: Edicion del fichero k8s.conf para el cortafuegos
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      create: yes
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1

  - name: Manejo del trafico del cortafuegos de kubernetes
    shell: sysctl --system
        
  - name: Quitar swap
    shell: swapoff -a

  - name: Comentando las entradas en in /etc/fstab
    replace:
      path: /etc/fstab
      regexp: '(^/.*swap*)'
      replace: '# \1'

  - name: Instalamos docker que será el engine para ejecutar contenedores.
    dnf:
      name: "{{ packages_docker_engine }}"
      enablerepo: "{{ repo }}"
      state: latest
      allowerasing: yes
    
  - name: Inicializando los servicios de docker
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items: "{{ services_docker_engine }}"      
    
  - name: Configurando el repositorio de kubernetes
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
  
  - name: Instalando Kubernetes
    dnf:
     name: "{{ packages }}"
     disable_excludes:  "{{ packages_disable_excludes }}"
     state: present
        
  - name: Inicializando los servicios
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items: "{{ services }}"   