---
- hosts: kubernetes-worker-nodes
  become: yes
  vars_files:
  - "group_vars/env_master.yaml"
  - "group_vars/env_workers.yaml"
 
  tasks:
  
  - name: Abre los puertos en el firewall
    firewalld:
      port: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    with_items: "{{ workers_ports }}"
    
  #- name: Obtenemos el token
  #  shell: cat "{{ token_file }}" | grep -e '\-\-token\s[^\s]*' -o
  #  register: token
  #  become: no
    
  #- name: Obtenemos el discovery token
  #  shell: cat "{{ token_file }}" | grep -e '\-\-discovery-token-ca-cert-hash.*$'
  #  register: discovery_token    
  #  become: no
    
  - name: Unimos el worker al cluster
    shell: cat "{{ token_file }}" | tail -2