---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Desabilita swap n el nodo
    shell: swapoff -a

  - name: Se comentan las entradas en /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(^/.*swap*)'
     replace: '# \1'