---
- hosts: kubernetes-master-nodes:kubernetes-worker-nodes
  become: yes
  vars_files:
  - env_var
  tasks:
  
  - name configurar DNS
    PTE
  
  - name: Activar transparent masquerading para que los PODs puedan comunicarse dentro del cluster mediante VXLAN:
    shell: 
        modprobe br_netfilter
        firewall-cmd --add-masquerade --permanent
        firewall-cmd --reload
        
  - name: Quitar swap
    shell: swapoff -a

  - name: Comentando als entradas en in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(^/.*swap*)'
     replace: '# \1'

  - name: Pone la IPs a /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"

  - name: Installing Docker and firewalld
    shell: |

  - name: Instalamos docker que será el engine para ejecutar contenedores.
    shell:
        dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
        dnf install docker-ce-19.03.14-3.el8 containerd.io -y
        systemctl enable docker
        systemctl start docker
        
  - name: Installing required packages
    dnf:
    name: "{{ packages }}"
    state: present
        
- name: Inicializando los servicios
    service:
    name: "{{ item }}"
    state: started
    enabled: yes
    with_items: "{{ services }}"      
